### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by wehddn** [martin-feaux/heptagon-lang#2]
The language lacks the keywords until and continue. 

Here is a usage example from the tutorial:
_Transitions with memory are denoted until e continue S (resp. unless e continue S): in that case, the target state S is executed without reset._

**Comment by wehddn** [comment]
I created pull request #1

**Comment by martin-feaux** [comment]
Thank you for the contribution.

**Comment by Mylloon** [comment]
is it possible to release a new version that includes the contribution?
